### ISSUE TITLE
Input for 4337 checklist

### ISSUE THREAD

**Issue by gpersoon** [aviggiano/security#2]
Here is some input the for checklist, that will require some structuring

Other chains:

Does the L2 chain support eth_sendRawTransactionConditional?
https://blog.oplabs.co/erc-4337-and-account-abstraction/
https://notes.ethereum.org/@yoav/SkaX2lS9j
https://github.com/maticnetwork/bor/pull/700
https://forum.arbitrum.foundation/t/aip-2-activate-support-for-account-abstraction-endpoint-on-one-and-nova/14790

Does the chain (plan to) support rip-7560?
https://github.com/eth-infinitism/RIPs/blob/native_account_abstraction/RIPS/rip-7560.md

Does the factory allow anyone to add stake to the entrypoint? 
In that case the unstakeDelay may not be changed (could be set to high value and then prevents unstake)

Does the wallet support the latest Entrypoint contract?
https://github.com/eth-infinitism/account-abstraction/releases

Does the wallet only access storage fields that are associated with the sender?
Otherwise that standard bundlers won't support it
https://eips.ethereum.org/EIPS/eip-4337#storage-associated-with-an-address

Is the wallet proxy based?
If so, which proxy is used?
If its an ERC1967Proxy, does it comply to the standard?

Can the smart contract account be converted to another type of smart contract account (via the proxy pattern)?
Could the initalizable storage slot be reused? See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4782

Does the wallet account support modules?
If so what type? 
- Delegate call based:
  - https://docs.zerodev.app/extend-wallets/overview
  - diamond pattern EIP-2535
  - safe
- Call based
  - https://eips.ethereum.org/EIPS/eip-6900
  - Universal Profile (slightly different) https://github.com/lukso-network/LIPs/tree/main/LSPs
 
Does it comply to the specs?
If delegatecall is used (e.g. Safe modules): no storage slots overlaps
What is the process the review modules?
What is the process to register modules?

Does the wallet support session keys?
https://www.biconomy.io/post/modular-session-keys
https://docs.zerodev.app/blog/session-keys-are-the-jwts-of-web3
https://docs.zerodev.app/use-wallets/use-session-keys
https://mirror.xyz/matchboxdao.eth/VXOvLKIvfXHP-cusKHw55zqlHpvvWwzh_fqm6j48Yek

Checks for applications using erc-4337
Do applications use ERC-6492: Signature Validation for Predeploy Contracts?
If so it comply to the standard?
https://eips.ethereum.org/EIPS/eip-6492 Signature Validation for Predeploy Contracts

- trivial things - signature check (erc1271), not using tx.origin
- gas assumptions: always use estimate, don't assume specific cost, like the 21000 fixed cost of "transfer" 
- support batching (not required, but can greatly improve UX)
- Support paymaster: (e.g. pay gas with the token I'm converting) 

Links
https://hacken.io/discover/erc-4337-account-abstraction/

**Comment by aviggiano** [comment]
Hi @gpersoon,

Thank you for the contribution, it's great! 
I will review this in more detail and integrate each point into the existing checklist. I'll ping you after I have a new version ready and will ask for feedback once it's completed.
